version: "3"
services:
  app:
    build: .
    image: project_manager_wp_22:1.0
    ports:
      - 3000:3000
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "pm_wp_22"
